# Generated by Django 6.0.1 on 2026-02-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='quiz',
            name='quizzes_qui_is_publ_8ea5d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='quiz',
            name='quizzes_qui_created_48c994_idx',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.AddField(
            model_name='quiz',
            name='negative_marking',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='updated_at',
        ),
    ]
