# Generated by Django 6.0.1 on 2026-02-11 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
        ('pyqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyqattempt',
            name='pyq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='pyqs.previousyearquestion'),
        ),
    ]
