# Generated by Django 6.0.1 on 2026-02-23 20:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
        ('quizzes', '0003_alter_question_correct_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('user', 'quiz')},
        ),
    ]
