# Generated by Django 6.0.1 on 2026-02-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(help_text='Main content displayed on the topic page (HTML supported)'),
        ),
    ]
