# Generated by Django 6.0.1 on 2026-02-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
