# Generated by Django 6.0.1 on 2026-02-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badge',
            field=models.CharField(choices=[('New Author', 'New Author'), ('Verified Contributor', 'Verified Contributor'), ('Top Educator', 'Top Educator')], default='New Author', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Rising Author', 'Rising Author'), ('Trusted Author', 'Trusted Author'), ('Expert Author', 'Expert Author')], default='Beginner', max_length=20),
        ),
    ]
