# Generated by Django 6.0.1 on 2026-02-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
