# Generated by Django 6.0.1 on 2026-02-03 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_studymaterial_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studymaterial',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(upload_to='study_materials/'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Required only if material is rejected', null=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
