# Generated by Django 6.0.1 on 2026-02-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_studymaterial_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(upload_to='study_materials/'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
