# Generated by Django 6.0.1 on 2026-02-03 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_studymaterial_description_and_more'),
        ('topics', '0002_alter_topic_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='subject',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='topic',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='topics.topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
