# Generated by Django 6.0.1 on 2026-02-03 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_remove_studymaterial_subject_studymaterial_topic_and_more'),
        ('topics', '0002_alter_topic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='topics.topic'),
        ),
    ]
