# Generated by Django 6.0.1 on 2026-02-04 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_studymaterial_subject_alter_studymaterial_topic'),
        ('topics', '0003_alter_topic_options_remove_topic_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='topics.topic'),
        ),
    ]
