# Generated by Django 6.0.1 on 2026-02-23 17:51

import django.db.models.deletion
import materials.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_studymaterial_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studymaterial',
            options={},
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='topic',
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(upload_to='materials/', validators=[materials.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
