# Generated by Django 6.0.1 on 2026-02-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_alter_pyqattempt_pyq'),
        ('pyqs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreviousYearQuestion',
            new_name='PYQ',
        ),
    ]
